### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by veudal** [byronbytes/QuickLock#1]
Hi, just a little suggestion: how about adding a global shortcut key for this little programm, it would increase the usefulness definetly, even though WIN + L would also work, maybe it would improve your programm idea :)

**Comment by byronbytes** [comment]
You know, I really like this idea! I'll try to imploment it, since it is a lightweight tool overall, I could probably do something like this!

**Comment by byronbytes** [comment]
Sorry for not working on this project a lot, I've had school and a ton of other things in the way such as trying to balance workflows with different apps, I promise I'll try to work on this feature later tonight!

**Comment by SagMeinenNamen** [comment]
No problem, pretty relatable situation right now for me too, don't hurry, just notify me when you made it 👌

**Comment by byronbytes** [comment]
Alright, I think I managed to implement the feature!  I'll release a version right now, and let me know if it works!

**Comment by SagMeinenNamen** [comment]
Sadly it does not, first of all Keys.LCTRL does not get recognized for me, after i replaced it with Keys.ControlKey it still does not work, I debugged it, it seems like the event KeyDown does not get activated for unknown reasons even when I am in the Window.

**Comment by byronbytes** [comment]
Aha, I see... 

I'll try to research this more, maybe I accidentally typed the wrong keycode or forgot to call it.

**Comment by byronbytes** [comment]
I made another fix, try debugging it and telling me if it worked

Note: From 8:00 to 2:40 I'm using a chromebook instead of my actual computer on weekdays, vacation is coming up so I'll have tons of time to improve it

**Comment by SagMeinenNamen** [comment]
No it doesnt, I dont wont to be mean, but please try debugging it yourself and be sure to fix it until you notify me, it is very time consuming and not really nessecary.

**Comment by byronbytes** [comment]
Hello, I am very sorry about the inactivity, and I do admit, that was wrong of me to do.

Just a few updates about this suggestion:
1. I have still been looking into this
2. I'm researching if it's possible even when the window is minimized for QoL purposes
3. This feature will most likely release within the next or second next big release.


I have a lot of potential planned for this application, and I've been trying to do my best.

**Comment by SagMeinenNamen** [comment]
Great to hear that you want to improve the programm!

**Comment by byronbytes** [comment]
I have updated the program, and it now has an early version of the feature!

**Comment by SagMeinenNamen** [comment]
@byronbytes great improvments! I like the new customizations that are now avaible, but there is one problem I think. There is no keybind, it locks my PC when I press ANY key, this should not happen right?

**Comment by byronbytes** [comment]
> @byronbytes great improvments! I like the new customizations that are now avaible, but there is one problem I think. There is no keybind, it locks my PC when I press ANY key, this should not happen right?

OH, I did not notice this bug while debugging, This issue did not happen to me at all, very surprisingly.
Apparently it happens when you click any of the letter keys, with further debugging. 

I'll investigate this issue and update it asap, thank you very much for reporting this!

**Comment by byronbytes** [comment]
Update: I have figured out what was causing the update, there was a mistake in the code where it would detect the keybind, and instead of it detecting CTRL it would detect every key besides CTRL.

I will be rolling out an update within the next few days, with this being fixed and a new interface that is much more user-friendly,  more options such as keybinding, more power-options and more.

**Comment by byronbytes** [comment]
I have updated the application, and I'm extremely sorry when I said a few days, I had to factory reset my PC and life got in the way for a while, but I think I'm back on track. Let me know some feedback that I can implement!

**Comment by SagMeinenNamen** [comment]
> I have updated the application, and I'm extremely sorry when I said a few days, I had to factory reset my PC and life got in the way for a while, but I think I'm back on track. Let me know some feedback that I can implement!

I'm sorry for what happened to you, but I will check out the application tomorrow and ofc give some feedback, btw maybe if you would like to you can also give me some feedback :)

**Comment by byronbytes** [comment]
I think you have been extremely amazing and extremely patient. You started this bug report about 4 months ago, and here we are today, with the feature added (and will be getting a keybind feature soon).  Your feedback with the updates have been extremely supportive and I have been able to track bugs down with ease. 

I have to balance multiple projects with life, school, and LiteTools itself, and you were very understanding with it. Now, I'm still somewhat new to owning a business so feedback on how that's going would be greatly helpful. Also, I do have an email for inquiries about LiteTools and more which is matty@litetools.net 

I just want to say once more, thank you so much for helping.

**Comment by SagMeinenNamen** [comment]
I just compiled the updated source code, great improvement once again! The only thing I (still) noticed is that (at least for me) the Key combination does not work properly, it still locks when just pressing CTRL, maybe it is a issue on my side, but I would recommend you to test it out on multiple of your own devices if possible and check if it works the way it should

**Comment by byronbytes** [comment]
> I just compiled the updated source code, great improvement once again! The only thing I (still) noticed is that (at least for me) the Key combination does not work properly, it still locks when just pressing CTRL, maybe it is a issue on my side, but I would recommend you to test it out on multiple of your own devices if possible and check if it works the way it should

Yes, for now the locking system is a "one button" combination (set to CTRL), I've tweaked with adding "two button" combos, which will **definitely** be coming in the next release, with the addition of a rebind system (Had a plan to add it in this release, but I was hitting a serious deadline)

I had tinkered with a two button combo and for some reason it just wouldn't work no matter what I tested, and when I released v1.3.0 I accidentally left a piece of code that was meant for debugging, which did cause the every button locks the computer issue. (Took me a while to find out that was the error.). Although, that won't stop me from trying to add a multi-button combination in the next release.

I will test it out on multiple devices when I get the ability to so there are no errors when I release another version. :)

**Comment by byronbytes** [comment]
Hey! I wanted to let you know about the future of QuickLock so far.

I haven't forgotten about the project, but I have been burned out of coding which has led me to doing different hobbies. Development has been slowed down severely due to this, but soon enough I'll try to get back on track since I'm currently juggling 2 hobbies.

1. I am planning on moving repositories due to the setup of this repository not being able to be changed without the project corrupting. I will let you know when this happens.
2. I'm also looking for a good time to overhaul the project, such as giving it more functions, etc. For example, choosing what the lock keybind does, and also being able to disable the built in Windows one. 

This idea has a ton of potential which I will take action on.
